CHANGELOG.md
lib/src/multi_channel.dart
pubspec.yaml
test/multi_channel_test.dart

MultiChannel wasn't buffering incoming remote events if their virtual
channels hadn't been created locally yet.

Fix a race condition

---

CHANGELOG.md
lib/src/json_document_transformer.dart
pubspec.yaml

Previously the local `sink` didn't get its generic type inferred properly and you would get runtime errors on certain operations which are difficult to track down.

Fix JsonDocumentTransformer.bind for dart 2

---

CHANGELOG.md
lib/src/stream_channel_transformer.dart
test/stream_channel_test.dart

We had some unnecessary typed wrappers that were interfering with
runtime type arguments.
Closes #22

Fix a remaining Dart 2 issue

---

CHANGELOG.md
lib/src/multi_channel.dart
pubspec.yaml
test/multi_channel_test.dart

- Add generic type arguments to the classes and relevant fields.
- Explicitly indicate which arguments take a `StreamChannel<dynamic>`.
- Update the test for MultiChannel to use a consistent type.

Allow a type on MultiChannel

---

lib/src/isolate_channel.dart
pubspec.yaml

The extra wrapping of `StackTrace.current` can always be done by the
receiver.

Drop dependency on StackTrace

---

analysis_options.yaml
lib/src/isolate_channel.dart
lib/src/multi_channel.dart
test/disconnector_test.dart
test/isolate_channel_test.dart
test/json_document_transformer_test.dart
test/multi_channel_test.dart
test/stream_channel_completer_test.dart
test/stream_channel_controller_test.dart
test/with_close_guarantee_test.dart
test/with_guarantees_test.dart

Fixes #29
Using the lint catches a bug were an uninitialized variable was causing
an intantiation to pick up a reified type of `dynamic` instead of a
useful type.

Enable prefer_typing_unitialized_varables lint

---

CHANGELOG.md
lib/src/isolate_channel.dart
pubspec.yaml
test/isolate_channel_test.dart

Fixes #29
- Add a type on the IsolateChannel in one of the tests so that it
exhibits the problem when run in Dart 2 mode.
- Cast the streams coming from the ReceivePort instances to the
appropriate types since ReceivePort is always `Stream<dynamic>`.
- Remove the type on the subscription variable since it's a subscription
on a dynamic stream and otherwise would never have the correct type.

Cast streams to correct types in IsolateChannel

---

CHANGELOG.md
lib/src/close_guarantee_channel.dart
lib/src/disconnector.dart
lib/src/guarantee_channel.dart
lib/src/isolate_channel.dart
lib/src/json_document_transformer.dart
lib/src/multi_channel.dart
lib/src/stream_channel_completer.dart
lib/src/stream_channel_controller.dart
lib/src/stream_channel_transformer.dart
lib/stream_channel.dart
pubspec.yaml
test/disconnector_test.dart
test/isolate_channel_test.dart
test/json_document_transformer_test.dart
test/multi_channel_test.dart
test/stream_channel_completer_test.dart
test/stream_channel_controller_test.dart
test/stream_channel_test.dart
test/with_close_guarantee_test.dart
test/with_guarantees_test.dart

- Run `dartfmt --fix`.
- Update version to start working towards next breaking change.
- Update minimum SDK to 2.0.0 stable.

Remove optional new/const

---

CHANGELOG.md
lib/isolate_channel.dart
pubspec.yaml
test/isolate_channel_test.dart

This will allow us to move to this import in the few packages which are
using this class, like test, without having a fully broken state in
between, and without required `git` dependency overrides.

Add separate import for `IsolateChannel`

---

CHANGELOG.md
lib/isolate_channel.dart
lib/stream_channel.dart
pubspec.yaml

Fixes #36 
This allows the default import to work without triggering any warnings
on the web due to transitively importing `dart:isolate`. This is
required to allow restricting imports based on platform.

Move isolate_channel to it's own import

---

CHANGELOG.md
lib/src/json_document_transformer.dart
test/json_document_transformer_test.dart

Closes #34
This was only used through the top level variable `jsonDocument` and no
use cases have surfaced for being able to pass a `reviver` or
`toEncodable` callback.
This implementation does no use `StreamChannelTransformer.fromCodec`
with a `JsonCodec` since the encoder and decoder are not 1:1.
- Remove the `JsonCodec` field and use `jsonEncode` and `jsonDecode`
calls directly.
- Move the detailed doc to `jsonDocument`.
- Make the class private.
- Remove the tests constructing the class directly.

Hide JsonDocumentTransformer

---

CHANGELOG.md
lib/src/close_guarantee_channel.dart
lib/src/disconnector.dart
lib/src/guarantee_channel.dart
test/disconnector_test.dart

Closes #35
It looks less like a potential bug and more explicitly expresses that
these functions don't return useful values.

Change all bare Future to Future<void>

---

analysis_options.yaml
pubspec.yaml
test/disconnector_test.dart
test/isolate_channel_test.dart
test/multi_channel_test.dart
test/stream_channel_completer_test.dart
test/stream_channel_test.dart
test/with_close_guarantee_test.dart
test/with_guarantees_test.dart

(Alternatively I could ignore the unawaited_futures lint, in each file or in analysis options)

Use pedantic lints

---

lib/src/close_guarantee_channel.dart
lib/src/disconnector.dart
lib/src/guarantee_channel.dart
lib/src/multi_channel.dart
lib/src/stream_channel_completer.dart
lib/stream_channel.dart
test/disconnector_test.dart
test/isolate_channel_test.dart
test/json_document_transformer_test.dart
test/multi_channel_test.dart
test/stream_channel_completer_test.dart
test/stream_channel_controller_test.dart
test/stream_channel_test.dart
test/with_close_guarantee_test.dart
test/with_guarantees_test.dart

- use_function_type_syntax_for_parameters
- prefer_single_quotes

Fix newly enforce package:pedantic lints

---

test/isolate_channel_test.dart

Without closing this channel the VM will not exit. Refactor to
`async/await` so that we can close the channel only after receiving the
expected items. This allows running the test directly in the VM without
the test runner.

Close send channel in test

---

lib/stream_channel.dart

This will be the type going forward. Keep a reference to `CastError` for
now, we can drop it after a few SDK releases.

Rewrite doc comment to refer to TypeError

---

CHANGELOG.md
pubspec.yaml

Resolves a warning from the pub tool that this field is no longer used.

Remove the author section from pubspec

---

lib/src/stream_channel_completer.dart

The only members of dart:async used here (Future and/or Stream) are exported from dart:core now.

Remove unused dart:async import

---

lib/src/json_document_transformer.dart

This reverts commit 9e331f3e2be06b57962e261e8a1574c65fe9a5b6.
Since this has not been published or rolled through to the SDK or
Flutter we will hold it back to reduce risk.

Revert "Remove unnecessary import"

---

CHANGELOG.md
lib/src/multi_channel.dart

When running in wasm, a number in a `List` will be parsed as a `double`. On the web the `as int` cast succeeds, but in dart2wasm it fails. Cast to `num` and use `toInt()` to more reliably get an `int` value.

Handle non-int multichannel message IDs

---

.github/workflows/no-response.yml
.github/workflows/publish.yaml

This PR contains changes created by the blast repo tool.
- `auto-publish`
- `github-actions`
- `no-response`

blast repo changes: auto-publish, github-actions, no-response
